name: Pytools_ferramentas

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10.2
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.2
    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip 
        pip install -r requirements-dev.txt
        pip install codecov
    - name: Lint with flake8
      run: |
          # stop the build if there are Python syntax errors or undefined names 
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    - name: pytest-coverage-commentator
      uses: coroo/pytest-coverage-commentator@v1.0.2
      with:
        pytest-coverage: pytest-coverage.txt

        
        
